name: Container Workflow
on:
  push:
  workflow_dispatch:

env:
  ACR_LOGON_SERVER: ${{ secrets.ACR_NAME_DEMO }}.azurecr.io
  IMAGE_NAME: ${{ secrets.ACR_NAME_DEMO }}.azurecr.io/webapp:${{ github.sha }}

jobs:
    build-deploy-image:
        
        runs-on: ubuntu-latest
        
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ env.ACR_LOGON_SERVER }}
            username: ${{ secrets.SERVICE_PRINCIPAL_ID_DEMO }}
            password: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD_DEMO }}

        - run: docker build --file DockerDeployDemoVS22Ent/Dockerfile --tag ${{ env.IMAGE_NAME }} . 
        #  docker build . -t ${{ env.IMAGE_NAME }}
        - run: docker push ${{ env.IMAGE_NAME }}
    
    
